### ISSUE TITLE
hey thanks for remaking this extension - a few questions

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [hrj/sloth#5]
on the description of https://chrome.google.com/webstore/detail/sloth/filkeckmpdjogddcamkafnekhgfaehkc

it says, "Where there are hundreds of tabs open in the session, a couple of them sneak through and become active. This limitation is due to the design of the browser."

wanted to know if this was solved, if not im able to test it in the future since i always have 'run chrome in background on' for g-calendar notification via an extension 

--

i dont know programming yet

but for those that do, are you able to tell how if something would have good performance
and memory usage?

https://chrome.google.com/webstore/detail/laziest-load/mgmkfbapiafkaebchhbghgffkfcmolhb
goes to https://github.com/hwangas/lazyload

https://chrome.google.com/webstore/detail/lazy-tabs/aabgbgciohhaogajcnacpgilhmacdahc
goes to https://github.com/jman/lazy_tab

--

i wish the naming was better cos it's super hard to find in the chrome store
but chrome ranking/search algorithm isnt very good anyhow
hard to find good things

**Comment by hrj** [comment]
> wanted to know if this was solved

No, Chromium has this limitation by design. See #1 

----

Quickly glanced through the other projects.

https://github.com/hwangas/lazyload is old, hacky and doesn't use the new discard API available from Chrome 54+. It's will consume more resources.

https://github.com/jman/lazy_tab seems to use similar design as this project. Not much different. This project has an additional feature; a blank tab is created so that no tabs are loaded on startup.

-----

Naming is tricky. If everyone uses similar names / keywords, it gets lost in the noise. To help discovery, I hope the extension gets better ranking / word-of-mouth publicity.

cheers!
